### ISSUE TITLE
No README!!

### ISSUE THREAD

**Issue by busterbeam** [Benwager12/EPOS3#1]
This is no good, without a readme... How do we build? or know what this does??

**Comment by Benwager12** [comment]
I may create a readme in future however for purposes of this issue, this is an electronic point of sale system that I made for my A level coursework. It automatically generates some sort of basic data when you start it up and build it, I've never put a project into vb before so I wasn't quite sure how to move it across.

**Comment by busterbeam** [comment]
I kind of guessed it was point of sale system, but almost all and any program should come with a README.  It doesn't need to be complicated README, just one that explains simply what this is or what it does.  Also remember Github defaults to showing README's when people view your repo.

Looks like some neat code👍️

**Comment by busterbeam** [comment]
I've submitted a pull request for this now.  If you want to accept and use it now
