### ISSUE TITLE
Terrible documentation

### ISSUE THREAD

**Issue by u7w2** [Benwager12/EPOS3#2]
The wiki is empty, there is no readme.md, no instructions on how to compile or any dependencies.
And worst of all, you used spaces instead of tabs!
:P

**Comment by Benwager12** [comment]
This has been a closed project for over 6 months, I decided to unprivate it so a few of my close friends could see it

**Comment by u7w2** [comment]
> This has been a closed project for over 6 months, I decided to unprivate it so a few of my close friends could see it

I think I'm friends with one of those close friends haha
